<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>lo_dev</name>
  <version>0.0.0</version>

  <description>
    This is a ROS2 implementation of lidar odometry.
  </description>

  <maintainer email="ysugano@andrew.cmu.edu">Yuhei Sugano</maintainer>

  <license>CERLAB</license>
 
  <buildtool_depend>amend_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>tf2</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>pcl_msgs</depend> 
  <depend>image_transport</depend>
  <!-- <depend>tf_conversions</depend> -->
  <depend>pcl_conversion</depend>
  <depend>sophus</depend>
  <!-- <depend>livox_ros_driver2</depend> -->
  
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
