/**:
  ros__parameters:
    # imu_topic: "/sim_imu"   # Isaac Sim
    # lidar_topic: "/sim_lidar/point_cloud"   # Isaac Sim
    # imu_topic: "/automine/imu"   # AutoMine
    # lidar_topic: "/automine/lidar"   # AutoMine
    imu_topic: "/imu_raw"   # KITTI
    lidar_topic: "/points_raw"   # KITTI
    # sensor: "ouster"    # Isaac Sim, AutoMine
    sensor: "velodyne"    # KITTI
    
    # world_frame: "map"
    # sensor_frame: "sensor"
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    imu_frame: "imu_link"
    lidar_frame: "lidar_link"

    imu_acc_x_limit: 0.5
    imu_acc_y_limit: 0.2
    imu_acc_z_limit: 0.4

    frontend_node:
        # ---- for general ----
        set_main_process_timer: true # default: true

        # ---- for voxel map ----
        use_voxel_map: true     # true: kiss-icp based voxel map / false: naive point cloud vector + pcl.kdtree search
        voxel_size: 1.0
        # voxel_size: 2.0
        # voxel_size: 0.5
        # voxel_size: 0.1
        voxel_max_distance: 100.0
        # voxel_max_distance: 1000.0
        max_points_per_voxel: 20 # [current best]
        # max_points_per_voxel: 50 
        turn_on_voxel_downsample: true
        # voxel_downsample_resolution_raw_to_mapping: 0.5 # following kiss-icp parameter
        # voxel_downsample_resolution_raw_to_mapping: 0.25    # One that went well (but slow) [current best]
        voxel_downsample_resolution: 0.75
        # voxel_downsample_resolution: 0.25
        # voxel_downsample_resolution_mapping_to_icpsource: 1.5 # following kiss-icp parameter
        voxel_downsample_resolution_mapping_to_icpsource: 0.5    # One that went well (but slow) [current best]
        threshold_voxel_nn_search_radius: 1.67 # vehicle 60km/h=16.7m/sec, lidar scan 0.1fps, 16.7x0.1=1.67m

        # ---- for preprocesing ----
        scan_line: 32 
        lidar_min_range: 5.0
        filter_point_size: 3
        enable_min_range_filter: false

        # ---- for lidar odometry ----
        # max_iterations: 5
        max_iterations: 25                # This is also important
        # max_iterations: 50              # This is also important [current best]
        # max_solver_time_in_seconds: 0.2   [current best]
        max_solver_time_in_seconds: 0.015     # 0.015 in liliom
        voxel_filter_size: 0.4      # pcl::voxelfiltersize()
        max_cloud_frame_for_local_map: 5
        # icp_iteration_num: 10           # This is super important [current best] works but kind of slow
        # icp_iteration_num: 5              # 5 and 7 does not work
        icp_iteration_num: 20           # for QP active set, 20 sounds too many but runs in real-time pretty much
        use_liosam_gauss_newton: false
        use_fastlio_point_plane_residual_param: true    # default: true
        build_local_map_from_all_global_map: false
        
        # ---- for factor graph ----
        turn_on_factor_graph: false 
        lidar_correction_noise: 0.01
        acc_n: 3.9939570888238808e-03          # accelerometer measurement noise standard deviation. #0.2
        gyr_n: 1.5636343949698187e-03         # gyroscope measurement noise standard deviation.     #0.05
        acc_w: 6.4356659353532566e-05          # accelerometer bias random work noise standard deviation.  #0.02
        gyr_w: 3.5640318696367613e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5
        g_norm: 9.80511    # 0 means you need to provide both imu-camera and laser-camera extrinsic
        lag: 1.0
        use_lo_prior_factor_wo_between_factor: false

        # ---- for inequality constraints ----
        turn_on_qp_ineq_constraints_active_set: true
        sqp_iteration_num_qp_active_set: 5
        turn_on_levenberg_marquardt_qp_active_set: true   # true: LM method, false: Gauss Netwon
        levenberg_marquardt_lambda_qp_active_set: 1.0
        turn_on_levenberg_marquardt_qp_active_set_marquardt_damping: true # true: JTJ+lambda*(diag(JTJ)) damping, false: JTJ+lambda*I damping,  
        turn_on_robust_kernel_qp_active_set: true
        turn_on_mad_based_scaling_for_kernel_weights_qp_active_set: true
        robust_kernel_qp_active_set: "Huber"
        turn_on_jacobian_column_scaling_qp_active_set: false
        pose_increment_multiplication: "right"  # "right": right Jacobian, "left": left Jacobian
        turn_on_Sophus_SE3_update: false
        qp_active_set_Hessian_computation: "for_loop" # "matrix_multiplication" or "for_loop"
        

    debug:
        print_imu_forward_propagation_state: false
        print_get_imu_pose_at_measurement_time: false
        print_imu_pose_timeline: false
        print_deskew_pointcloud: false
        print_initial_guess_lo: false
        print_relative_transform_lo: false
        print_num_residuals: false
        print_point_plane_residual_preparation: false
        print_scan_imu_time_sync: false
        print_first_point_in_current_scan: false
        print_cloud_map_size: false
        print_keyframe_id: false
        print_lo_relative_pose_fg: false
        print_PreintegratedImuMeasurements_fg: false
        print_imu_factor_fg: false
        print_imu_bias_factor_fg: false
        print_lo_factor_fg: false
        print_imu_prop_state_fg: false
        print_estimated_state_fg: false
        print_published_pose: false
        print_key_timestamp_in_window: false
        print_num_factors_values: false
        print_num_downsampled_point: false
        print_num_point_in_voxel_map: false
        dump_log_file_voxel_ids: false
        print_qp_active_set: false
        print_qp_active_set_init_guess: false
        print_qp_active_set_matrices_jacobian_residual: false   # can be too many printed lines
        print_qp_active_set_matrices: false
        print_qp_active_set_solution_analysis: false
        print_qp_active_set_solution: false
        print_qp_active_set_solution_pose_update: false
        print_qp_icp_iter_num: false
        print_qp_sqp_iter_num: false
        try_qp_active_set_Cholesky_Decomposition_unconstrained: false

    init:
        imu_init_fastlio2: false

    imu:
        isotropic_scale_calibration_to_G: false
        enalbe_init_guess_for_lo: true


    ## Isaac Sim
    # # Orientation of lidar frame w.r.t. imu frame
    # R_imu_lidar: [1.0, 0.0, 0.0,
    #               0.0, 1.0, 0.0,
    #               0.0, 0.0, 1.0]
    # # Translation of lidar frame w.r.t. imu frame
    # t_imu_lidar: [0.0, 0.0, 0.0]


    ## AutoMine OCT-00
    # Orientation of lidar frame w.r.t. imu frame
    # R_imu_lidar: [9.99991000e-01, -4.00790000e-03, -1.57277000e-03,
    #               4.03242000e-03,  9.99865000e-01,  1.59156000e-02,
    #               1.50877000e-03, -1.59218000e-02,  9.99872000e-01]
    # Translation of lidar frame w.r.t. imu frame
    # t_imu_lidar: [1.64752937e+00, -1.83728126e-02, 4.37729539e-01]


    ## KITTI
    # # Orientation of lidar frame w.r.t. imu frame
    R_imu_lidar: [ 9.99997600e-01, -7.85402700e-04,  2.02440600e-03,
                   7.55307100e-04,  9.99889800e-01,  1.48245400e-02,
                  -2.03582600e-03, -1.48229800e-02,  9.99888100e-01 ]
    # # Translation of lidar frame w.r.t. imu frame
    t_imu_lidar: [ 8.10543903e-01, -3.07054359e-01, 8.02724058e-01]




    # Always identity in this livo, but explicitly declared for clarity
    # Orientation of imu frame w.r.t. base_link
    R_base_imu: [1.0, 0.0, 0.0,
                  0.0, 1.0, 0.0,
                  0.0, 0.0, 1.0]
    # Translation of imu frame w.r.t. base_link
    t_base_imu: [0.0, 0.0, 0.0]

    # Always identity in this livo, but explicitly declared for clarity
    # Orientation of odom frame w.r.t. map frame
    R_map_odom: [1.0, 0.0, 0.0,
                  0.0, 1.0, 0.0,
                  0.0, 0.0, 1.0]
    # Translation of odom frame w.r.t. map frame
    t_map_odom: [0.0, 0.0, 0.0]
